#!/bin/sh

# $FreeBSD$
#
# PROVIDE: knxd
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# knxd_enable (bool):	Set to NO by default.
#				Set it to YES to enable doormand.

. /etc/rc.subr

name=knxd
rcvar=knxd_enable
pidfile="/var/run/knxd.pid"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

knxd_user="smarthome"

knxd_start()
{
	/usr/local/bin/knxd /etc/knxd.ini
}

knxd_stop()
{
        if [ -e "${pidfile}" ]; then
                kill -s TERM `cat ${pidfile}`
        else
                echo "${name} is not running"
        fi
}


load_rc_config $name
: ${knxd_enable:=no}

run_rc_command "$1"
