#!/bin/sh

# $FreeBSD$
#
# PROVIDE: smarthomeng
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# smarthomeng_enable (bool):	Set to NO by default.
#				Set it to YES to enable doormand.

. /etc/rc.subr

name=smarthomeng
rcvar=smarthomeng_enable
pidfile="/usr/local/smarthome/var/run/smarthome.pid"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

smarthomeng_user="smarthome"

smarthomeng_start()
{
	/usr/local/bin/python3 /usr/local/smarthome/bin/smarthome.py
}

smarthomeng_stop()
{
        if [ -e "${pidfile}" ]; then
                kill -s TERM `cat ${pidfile}`
        else
                echo "${name} is not running"
        fi
}


load_rc_config $name
: ${smarthomeng_enable:=no}

run_rc_command "$1"
